export const variantConfig = {
  default: {
    bgColor: "bg-gray-50",
    textColor: "text-gray-600",
    valueColor: "text-gray-800",
    iconBg: "bg-gray-100",
    iconColor: "text-gray-600",
    border: "border-gray-200",
  },
  blue: {
    bgColor: "bg-blue-50",
    textColor: "text-blue-600",
    valueColor: "text-blue-700",
    iconBg: "bg-blue-100",
    iconColor: "text-blue-600",
    border: "border-blue-200",
  },
  green: {
    bgColor: "bg-green-50",
    textColor: "text-green-600",
    valueColor: "text-green-700",
    iconBg: "bg-green-100",
    iconColor: "text-green-600",
    border: "border-green-200",
  },
  purple: {
    bgColor: "bg-purple-50",
    textColor: "text-purple-600",
    valueColor: "text-purple-700",
    iconBg: "bg-purple-100",
    iconColor: "text-purple-600",
    border: "border-purple-200",
  },
  orange: {
    bgColor: "bg-orange-50",
    textColor: "text-orange-600",
    valueColor: "text-orange-700",
    iconBg: "bg-orange-100",
    iconColor: "text-orange-600",
    border: "border-orange-200",
  },
  red: {
    bgColor: "bg-red-50",
    textColor: "text-red-600",
    valueColor: "text-red-700",
    iconBg: "bg-red-100",
    iconColor: "text-red-600",
    border: "border-red-200",
  },
  yellow: {
    bgColor: "bg-yellow-50",
    textColor: "text-yellow-600",
    valueColor: "text-yellow-700",
    iconBg: "bg-yellow-100",
    iconColor: "text-yellow-600",
    border: "border-yellow-200",
  },
};
